#ifndef _UI_MSG_CODE_H
#define _UI_MSG_CODE_H


enum {
    UI_MSG_CODE_TIME_REFRESH = 0,
    UI_MSG_CODE_LIGHT,
    UI_MSG_CODE_REFRESH_PHASE,
    UI_MSG_CODE_RSSI,
    UI_MSG_CODE_SEND_LORA,
    UI_MSG_CODE_ACK,
    UI_MSG_CODE_LORA1_RCV,
    UI_MSG_CODE_LORA2_RCV,
    UI_MSG_CODE_ID_CHANGE,
};


#endif
