#define VERSION_MAJOR 2
#define VERSION_MINOR 7
#define VERSION_PATCH 1
#define VERSION_BUILD 0
#define VERSION_UINT32                                            \
  (VERSION_MAJOR | (VERSION_MINOR << 8) | (VERSION_PATCH << 16) | \
   (VERSION_BUILD << 24))

#define FIX_VERSION_MAJOR VERSION_MAJOR
#define FIX_VERSION_MINOR VERSION_MINOR
#define FIX_VERSION_PATCH VERSION_PATCH
#define FIX_VERSION_BUILD VERSION_BUILD
#define FIX_VERSION_UINT32                                            \
  (FIX_VERSION_MAJOR | (FIX_VERSION_MINOR << 8) | (FIX_VERSION_PATCH << 16) | \
   (FIX_VERSION_BUILD << 24))


#define VERSION_MONOTONIC 1
